name: CI

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - '**.go'
      - 'Makefile'
      - 'go.**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/github.com/${{ github.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
        with:
          path: ./src/github.com/${{ github.repository }}
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Cache Go modules
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # v3.0.11
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Lint
        run: make build
